using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventSystem.Core.Migrations
{
    /// <inheritdoc />
    public partial class CreateAuditLogsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AuditLogs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Action" text NOT NULL,
                    "EntityType" text NOT NULL,
                    "EntityId" integer,
                    "Details" text,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UserId" integer NOT NULL,
                    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId")
                        REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");
                CREATE INDEX IF NOT EXISTS "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "AuditLogs";""");
        }
    }
}
